stages:
  - deploy_to_gitlab

deploy_to_gitlab:
  stage: deploy_to_gitlab
  image: node:16
  script:
    - npm install -g @angular/cli
    - git clone --mirror https://github.com/anorangefalcon/eCommerce-frontend.git
    - cd your-angular-repo.git
    - git remote add gitlab https://gitlab.com/priyanshu.dhall/eCommerce-frontend.git
    - git push --mirror gitlab
  only:
    - dev
